apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-app
        image: "{{ .Values.frontend.repository | default "meu-frontend" }}:{{ .Values.frontend.tag }}"
        imagePullPolicy: Never
        ports:
        - containerPort: {{ .Values.frontend.containerPort }}
        resources:
          requests:
            memory: {{ .Values.frontend.resources.requests.memory | quote }}
            cpu: {{ .Values.frontend.resources.requests.cpu | quote }}
          limits:
            memory: {{ .Values.frontend.resources.limits.memory | quote }}
            cpu: {{ .Values.frontend.resources.limits.cpu | quote }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.frontend.containerPort }}
          initialDelaySeconds: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.frontend.containerPort }}
          initialDelaySeconds: 1
          periodSeconds: 5