backend:
  replicas: 1
  repository: meu-backend
  tag: "f6c050e"
  containerPort: 3000
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "200m"
frontend:
  replicas: 1
  repository: meu-frontend
  tag: "9804417"
  containerPort: 80
  nodePort: 30080
  resources:
    requests:
      memory: "32Mi"
      cpu: "50m"
    limits:
      memory: "64Mi"
      cpu: "100m"
