name: Backend CI

on:
  push:
    branches: [ main, master ]
    paths:
      - 'backend/**' # Só dispara se houver alterações na pasta backend

jobs:
  build-backend:
    runs-on: self-hosted

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4

    - name: Build da Imagem Docker Backend
      run: |
        echo "Iniciando o build da imagem do backend..."
        docker build -t meu-backend:${{ github.sha }} ./backend
        docker tag meu-backend:${{ github.sha }} meu-backend:latest

    - name: Exportar Imagem para TAR
      run: |
        echo "Gerando o arquivo TAR da imagem do backend..."
        docker save meu-backend:${{ github.sha }} -o backend.tar

    - name: Injetar TAR no Cluster Kind
      run: |
        echo "Enviando o TAR para dentro do nó do Kind..."
        sudo /usr/local/bin/kind load image-archive backend.tar --name k8s-local
        rm backend.tar
        echo "Imagem do Backend injetada com sucesso!"