name: Backend CI

on:
  push:
    branches: [ main, master ]
    paths:
      - 'backend/**'

jobs:
  build-backend:
    runs-on: self-hosted

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Baixar o Kind Local na Pipeline
      run: |
        echo "Baixando o binário do Kind para a workspace do Runner..."
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64
        chmod +x ./kind

    - name: Build, Injeção e Atualização do GitOps
      env:
        DOCKER_HOST: tcp://192.168.100.11:2375
      run: |
        # Gera tag curta baseada no SHA do commit (ex: e4f5a2b)
        TAG_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
        
        echo "1. Fazendo o build remoto usando o Docker da VM do Kubernetes..."
        docker build -t meu-backend:$TAG_SHA ./backend
        
        echo "2. Injetando a imagem no Kind usando o Docker remoto..."
        ./kind load docker-image meu-backend:$TAG_SHA --name k8s-local
        
        echo "3. Baixando o YQ para editar o YAML..."
        curl -sL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o ./yq && chmod +x ./yq
        
        echo "4. Atualizando a tag do backend no values.yaml..."
        ./yq -i ".backend.tag = \"$TAG_SHA\"" meu-app-chart/values.yaml
        
        echo "5. Comitando a nova tag de volta no repositório com Rebase..."
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add meu-app-chart/values.yaml
        
        # O || echo evita que a pipeline falhe se o arquivo já estiver atualizado
        git commit -m "chore(gitops): atualizando tag do backend para $TAG_SHA [skip ci]" || echo "Sem alterações para comitar"
        
        # Puxa as alterações remotas mais recentes e reaplica o commit no topo (evita non-fast-forward)
        git pull --rebase origin ${{ github.ref_name }}
        
        # Envia de forma segura
        git push origin ${{ github.ref_name }}