name: Frontend CI

on:
  push:
    branches: [ main, master ]
    paths:
      - 'frontend/**' # Só dispara se houver alterações na pasta frontend

jobs:
  build-frontend:
    runs-on: self-hosted

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4

    - name: Baixar o Kind Local na Pipeline do Runner
      run: |
        echo "Baixando o binário do Kind para a workspace do Runner..."
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64
        chmod +x ./kind

    - name: Build e Injeção no Kind via Rede
      env:
        DOCKER_HOST: tcp://192.168.100.11:2375
      run: |
        echo "Fazendo o build remoto usando o Docker da VM do Kubernetes..."
        docker build -t meu-frontend:${{ github.sha }} ./frontend
        docker tag meu-frontend:${{ github.sha }} meu-frontend:latest
        
        echo "Injetando a imagem no Kind usando o Docker remoto..."
        ./kind load docker-image meu-frontend:${{ github.sha }} --name k8s-local
        echo "Sucesso total no pipeline do Frontend!"