name: Frontend CI

on:
  push:
    branches: [ main, master ]
    paths:
      - 'frontend/**' # Só dispara se houver alterações na pasta frontend

jobs:
  build-frontend:
    runs-on: self-hosted

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4

    - name: Build da Imagem Docker Frontend
      run: |
        echo "Iniciando o build da imagem do frontend..."
        docker build -t meu-frontend:${{ github.sha }} ./frontend
        docker tag meu-frontend:${{ github.sha }} meu-frontend:latest

    - name: Exportar Imagem para TAR
      run: |
        echo "Gerando o arquivo TAR da imagem do frontend..."
        docker save meu-frontend:${{ github.sha }} -o frontend.tar

    - name: Injetar TAR no Cluster Kind
      run: |
        echo "Enviando o TAR para dentro do nó do Kind..."
        sudo /usr/local/bin/kind load image-archive frontend.tar --name k8s-local
        rm frontend.tar
        echo "Imagem do Frontend injetada com sucesso!"